name: Protect Hotfix and Release Branches

on:
  create:
    branches:
      - 'hotfix/**'
      - 'release/**'
      - 'develop/**'

jobs:
  protect-branch:
    runs-on: ubuntu-latest
    steps:
      # - name: toronto-cli install & start
      #   uses: MobilityTechnologiesActions/internal-tools/toronto-cli@v0
      #   with:
      #     mot-toronto-token: ${{ secrets.MOT_TORONTO_TOKEN }}

      - name: Create branch protection
        uses: actions/github-script@v6
        if: startsWith(github.ref_name, 'topic/')
        with:
          github-token: ${{ secrets.BRANCH_PROTECTION_SECRETS }}
          script: |
            const branch = context.payload.ref;

            github.rest.repos.updateBranchProtection({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: branch,
              required_status_checks: {
                strict: false,
                contexts: []
              },
              enforce_admins: true,
              required_pull_request_reviews: {
                "required_approving_review_count": 1
              },
              restrictions: null
            })
