name: Protect Hotfix and Release Branches

on:
  push:
    branches:
      - 'hotfix/**'
      - 'release/**'

jobs:
  protect-branch:
    runs-on: ubuntu-latest

    permissions:
      contents: read # リポジトリ内容の読み取り権限
      actions: read # ワークフローに関する情報の読み取り権限
      issues: read # イシュー関連の情報の読み取り権限

    steps:
      - name: Protect branch from deletion
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          echo "Protecting branch: $BRANCH_NAME from deletion"

          gh api /repos/${{ github.repository }}
