name: Protect Hotfix and Release Branches

on:
  push:
    branches:
      - 'hotfix/**'
      - 'release/**'

jobs:
  protect-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Protect branch from deletion
        env:
          GITHUB_TOKEN: ${{ secrets.EDIT_BRANCH_RULES_SECRET }}
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          echo "Protecting branch: $BRANCH_NAME from deletion"

          gh api \
            --method PUT \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/go-sotaro-shibata/test-github-actions/branches/${BRANCH_NAME}/protection \
            -F "allow_fork_syncing=true"
